### ISSUE TITLE
Collaborator change

### ISSUE THREAD

**Issue by mjhorn-personal** [Resynova/CSC221-amjenkins2-GroupProject#1]
Hey austin, could you add me as a collaborator on this account? the username is mjhorn-personal, or email mjhorn.personal@gmail.com.

Thanks!

**Comment by Resynova** [comment]
Just did. Added both emails

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by mjhorn-personal** [comment]
Awesome, got it, thanks!
